feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
      stores:
        loggerLevel: full
logbook:
  include:
    - /**
  exclude:
    - /swagger-ui/**
    - /v3/api-docs/**
  filter:
    enabled: true
  format:
    style: http
  write:
    max-body-size: -1